name: trivia_numbers_clean_arch
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity: ^0.4.3+7
  http: ^0.12.0+2
  shared_preferences: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0   
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

